name: CI - Testes Automatizados

on:
  push:       # Aqui vai rodar os testes sempre quando houver um push
    branches: [main, develop]
  pull_request:  #  Aqui também vai rodar nos pull requests
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest  # Define o ambiente (No nosso caso vai ser no ubuntu mais reccente)

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3  # Faz o checkout do repositório para o ambiente CI

      - name: Configurar JDK 17
        uses: actions/setup-java@v3  # Configura a versão do Java
        with:
          java-version: 17
          distribution: 'temurin'  # OpenJDK build da Temurin

      - name: Instalar Dependências
        run: mvn install -DskipTests  # Aqui instala as dependências sem rodar testes ainda

      - name: Rodar Testes
        run: mvn test  # Aqui executa os testes do Maven

      - name: Verificar Resultados dos Testes
        if: failure()
        run: echo "Alguns testes falharam. Verificar logs."  # Mensagem em caso de falha