name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'  

      - name: Build with Maven
        run: mvn package
      - name: Copy WAR to Tomcat
        run: cp target/*.war /usr/local/tomcat/webapps/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Tomcat
        run: sudo service tomcat start
